source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'7.0'

use_frameworks!

target “LFLiveKitSwiftDemo” do
    pod 'LFLiveKit', :path => '../../.'
    pod 'GPUImage', :path=>'../../../GPUImage'
end
